teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      z: 0
    scale_linear:
      z: 1.0
    scale_linear_turbo:
      z: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 5  # R1 shoulder button
    enable_turbo_button: 4  # L1 shoulder button